lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_4/urls.py
from django.conf.urls import url
from .views import index, message_post, message_table

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
    url(r'^$', index, name='index'),
    url(r'^add_message', message_post, name='add_message'),
    url(r'^result_table', message_table, name='result_table'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
from django.views.generic.base import RedirectView
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10






urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1, namespace='lab-1')),
    url(r'^lab-2/', include(lab_2, namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3, namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),




    #---------------------------------------------------------------------
    url(r'^', RedirectView.as_view(permanent=True, url='/lab-4/')
            , name='index'),
    ]

lab_4/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Message(models.Model):
    name = models.CharField(max_length=27)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

lab_4/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }
    
    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

lab_4/views.py
from django.shortcuts import render
from lab_2.views import landing_page_content
from lab_1.views import mhs_name
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message

# Create your views here.
respone = {'author': mhs_name}
about_me = ['DotA','belajar','tidur','ngoding','makan','main']

def index(request):
    respone['content'] = landing_page_content
    html = 'lab_4/lab_4.html'
    respone['about_me'] = about_me
    respone['message_form'] = Message_Form
    return render(request, html, respone)

def message_post(request):
    form = Message_Form(request.POST or None)

    _POST_ = request.POST
    if(request.method == 'POST' and form.is_valid()):
        respone['name'] = _POST_['name'] if _POST_['name'] != "" else "Anonymous"
        respone['email'] = _POST_['email'] if _POST_['email'] != "" else "Anonymous"
        respone['message'] = _POST_['message']

        message = Message(
            name=respone['name'],
            email=respone['email'],
            message=respone['message']
        )
        message.save()
        html = 'lab_4/form_result.html'
        return render(request, html, respone)

    else:
        return HttpResponseRedirect('/lab_4')

def message_table(request):
    message = Message.objects.all()
    respone['message'] = message
    html = 'lab_4/table.html'
    return render(request, html, respone)

lab_4/templates/lab_4/form_result.html
<!DOCTYPE html>
<style>
    footer {
      position: relative;
      right: 0;
      bottom: 0;
      left: 0;
      padding: 1rem;
      background-color: #efefef;
      text-align: center;
      clear: both;
      z-index: 10;
      height: 5em;
      margin-top: 5em;
    }
</style>

{% extends "lab_4/layout/base.html" %}
{% block title %} Pesan dari {{ name }} {% endblock %}
{% block content %}
<textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;-{{name}} 
    by {{ email }}
</textarea>
{% endblock %}

{% block footer %}
    <p> &copy; {{name}} </p>
{% endblock %}

lab_4/templates/lab_4/lab_4.html
<!DOCTYPE html>
{% extends "lab_4/layout/base.html" %}

{% block content %}
<center>
<h1 class="h1">Portofolio</h1>
<img class="img-circle" style="width:250px; height:250px" src = "https://scontent.fcgk7-1.fna.fbcdn.net/v/t31.0-8/21950881_1824588787554595_8127152560897552906_o.jpg?_nc_eui2=v1%3AAeGJq6FykZfQHudjA7Li-eyHlhn55nVXoXpoMWMoSeNZv8NrWDgHmFMge_cvJ2fsF3r2FmWqASkVg2UfGE7L43tqb4cqtujxRba55YRCSgh-NIr5rr4WLSgMPpDjoZVBzHA&oh=398e3b4da494a8fbbb86edc77738e9e4&oe=5A868729">
<hr/>
<section name="bio">
    <h2>Bio</h2>
    <p>
        {{content}}
    </p>
</section>
<hr/>
<section name="about_me">
</center>
    <h2>List</h2>
    <ul>
        {% for ii in about_me %}
        <li> {{ ii }} </li>
        {% endfor %}
    </ul>
</section>
<hr/>
<center>
<section name="form">
    <h2>Send Message</h2>
    <form id="form" method="POST" action="{% url 'lab-4:add_message' %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</section>
</center>

{% endblock %}

lab_4/templates/lab_4/table.html
<!DOCTYPE html>
{% extends "lab_4/layout/base.html" %}

{% block title %} Kumpulan Pesan {% endblock %}

{% block content %}
<!--  Populate semua isi pesan dari model -->
<table class="table">
    <thead>
        <th>Nama</th>
        <th>Email</th>
        <th>Pesan</th>
        <th>Dibuat Pada</th>
    </thead>
    <tbody>
        <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
        {% for i in message %}
        {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
        <tr class="warning"> {% else %} <tr class="success">
            {% endif %}
            <td> {{i.name}} </td>
            <td> {{i.email}} </td>
            <td> {{i.message}} </td>
            <td> {{i.created_date}} </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}